name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache apt-packages for lftp
        uses: actions/cache@v4
        id: apt-cache # Ensure this id is set
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-lftp-${{ hashFiles('**/lockfiles') }} # Or your preferred key
          restore-keys: |
            ${{ runner.os }}-apt-lftp-

      - name: Install lftp
        run: |
          echo "Attempting to install lftp..."
          sudo apt-get install -y lftp
          echo "LFTP version:"
          lftp --version
          
      - name: Perform FTP Upload with lftp
        run: |
          echo "lftp will run here..."
          lftp -d -u "u765565545.renovajob,Re.No.VA1" ftp.img.kebenet.com -e "
            set ftp:ssl-allow no;
            set dns:order \"inet\"; # Often helpful
            mirror --reverse \
                   --delete-first \
                   --verbose \
                   --exclude-glob .git* \
                   --exclude .git/ \
                   --exclude .github/ \
                   src/ ;
            echo 'Mirror complete. Bye!';
            bye;
          "
          echo "FTP upload attempt finished."
          
      - name: Report deployment
        run: echo "Deployment to FTP server successful - KEBENET©"
