name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check if src directory exists and is not empty
        id: check_src
        run: |
          if [ -d "src" ] && [ "$(ls -A src)" ]; then
            echo "src_dir_status=true" >> $GITHUB_OUTPUT
          else
            echo "src_dir_status=false" >> $GITHUB_OUTPUT
          fi
      - name: Report src directory status
        if: always() # Ensures this step runs regardless of the previous step's outcome (within the job)
        run: |
          if [ "${{ steps.check_src.outputs.src_dir_status }}" == "true" ]; then
            echo "src/ directory found and is not empty. Proceeding with deployment."
          else
            echo "src/ directory not found or is empty. Skipping deployment."
          fi

      - name: Install lftp
        if: steps.check_src.outputs.src_dir_status == 'true'
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Perform FTP Upload with lftp
        if: steps.check_src.outputs.src_dir_status == 'true'
        run: |
          echo "lftp will run here..."
          lftp -d -u "$FTP_USER,$FTP_PASSWORD" $FTP_HOST -e "set ftp:ssl-allow no; mirror --reverse --delete-first --verbose --exclude-glob .git* --exclude .git/ --exclude .github/ src/ ;bye;"
        env: # Make sure secrets are available if used directly in run
          FTP_HOST: ftp.img.kebenet.com
          FTP_USER: u765565545.renovajob
          FTP_PASSWORD: Re.No.VA1

      - name: Report deployment outcome
        if: steps.check_src.outputs.src_dir_status == 'true'
        run: echo "Deployment to FTP server successful."
